[Network]
ServerRegion = 'Some region' # An identifier/name for the region, this is used for Sentry
PlayerManagerPath = 'players/manager.json' # The path with the player-list file
Whitelisted = false # If whitelist block is enabled
WhitelistPath = 'whitelist.json' # The path to the whitelist file
SecuredSlots = 0 # The amount of secured slots on the server for only whitelisted players
MaxRenderDistance = 16 # The view distance for players
FlushRate = 20 # The flush rate for the server
SentryDSN = '' # The DSN link of the sentry connection

[[Network.Servers]] # Server A: accepts connections from ':19132', redirects to ':19133'.
Name = 'Some server'
LocalAddress = '127.0.0.1:19132'
RemoteAddress = '127.0.0.1:19133'

# To append another server, just add another Network.Servers entry like this:

# [[Network.Servers]] # Server B: accepts connections from ':19032', redirects to ':19033'.
# Name = 'Another server'
# LocalAddress = '127.0.0.1:19032'
# RemoteAddress = '127.0.0.1:19033'

[Border]
Enabled = false # Whether to enable the world border
MinX = -12000 # The minimum X coordinate for the world border
MaxX = 12000 # The maximum X coordinate for the world border
MinZ = -12000 # The minimum Z coordinate for the world border
MaxZ = 12000 # The maximum Z coordinate for the world border

[PingIndicator]
Enabled = true # Whether to enable the ping indicator
Identifier = '&_playerPing:' # The identifier for the ping indicator

[AFKTimer]
Enabled = true # Whether to enable the afk timer
TimeoutDuration = "10m" # The timeout duration of the afk timer

[Resources]
PacksRequired = false # If resource packs are required to download by players
CommandPath = 'resources/commands.json' # The path to the file where the bds-scripting-commands are stored
URLResources = [] # Urls of resource packs to require downloaded by players
PathResources = [] # Paths of resource packs to require downloaded by players

[AuthenticationService]
Enabled = false # Whether this service is enabled
URL = 'http://127.0.0.1:8080/authentication' # The Hub API Endpoint to verify players joining through queue
Key = 'secret-key' # The authentication key for the queues API

[ClaimService]
Enabled = false # Whether this service is enabled
URL = 'http://127.0.0.1:3001/api/database/testing/table/claims' # The service endpoint to fetch players claims
Key = 'secret-key' # The API token needed to fetch claims

[VPNService]
Enabled = false # Whether this service is enabled
URL = 'http://ip-api.com/json' # A service to validate users if they are using VPN's
Key = '' # Authentication key if required

[Encryption]
Key = 'secret-key' # The Encryption key used for XUID messages to BDS
