services:
  gobds:
    container_name: gobds-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 19132:19132/udp
    volumes:
      - ./config/config.toml:/app/config.toml
      - ./whitelist.json:/app/whitelist.json
      - ./players:/app/players
      - ./resources:/app/resources
