name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/golang:1.24-alpine
          image: smellofcurry/gobds
        continue-on-error: true

      - name: Check if build is required
        id: check_build
        run: echo "build_needed=${{ github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true' || steps.baseupdatecheck.outcome == 'failure' }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: steps.check_build.outputs.build_needed == 'true'
        uses: docker/login-action@v2
        with:
          username: smellofcurry
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.check_build.outputs.build_needed == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        if: steps.check_build.outputs.build_needed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: smellofcurry/gobds:latest
